language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      before_install:
        # - brew update
        # - brew tap caskroom/cask
        - brew cask install powershell
    - os: linux
      dist: bionic
      # VM-based builds turned out to be faster
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main
              key_url: https://packages.microsoft.com/keys/microsoft.asc
          packages:
            - powershell

script:
  - pwsh -c "./test.ps1 -ci -passThru"

